/*
 * Recipe database for the Meal Plan app.
 *
 * Each recipe carries everything the four core features need:
 *   - meal plan creation & suggestions read `tags`, `mealTypes`, `calories`, `servings`
 *   - the shopping list reads `ingredients` (each with quantity + unit + aisle)
 *   - cooking instructions read `steps` and `prepTime` / `cookTime`
 *
 * Ingredient units are kept consistent so quantities can be summed across
 * recipes when building a shopping list (see js/shopping.js).
 */

const RECIPES = [
  {
    id: 'overnight-oats',
    name: 'Berry Overnight Oats',
    mealTypes: ['breakfast'],
    tags: ['vegetarian', 'quick', 'no-cook'],
    servings: 1,
    calories: 380,
    prepTime: 10,
    cookTime: 0,
    ingredients: [
      { item: 'rolled oats', qty: 0.5, unit: 'cup', aisle: 'Grains & Pasta' },
      { item: 'milk', qty: 0.5, unit: 'cup', aisle: 'Dairy & Eggs' },
      { item: 'plain yogurt', qty: 0.25, unit: 'cup', aisle: 'Dairy & Eggs' },
      { item: 'mixed berries', qty: 0.5, unit: 'cup', aisle: 'Produce' },
      { item: 'honey', qty: 1, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'chia seeds', qty: 1, unit: 'tsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Combine oats, milk, yogurt, honey and chia seeds in a jar or bowl.',
      'Stir well, then fold in half of the berries.',
      'Cover and refrigerate overnight (at least 4 hours).',
      'In the morning, top with the remaining berries and serve chilled.',
    ],
  },
  {
    id: 'veggie-scramble',
    name: 'Veggie Egg Scramble',
    mealTypes: ['breakfast'],
    tags: ['vegetarian', 'gluten-free', 'quick', 'high-protein'],
    servings: 2,
    calories: 320,
    prepTime: 10,
    cookTime: 10,
    ingredients: [
      { item: 'eggs', qty: 4, unit: 'unit', aisle: 'Dairy & Eggs' },
      { item: 'bell pepper', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'spinach', qty: 2, unit: 'cup', aisle: 'Produce' },
      { item: 'onion', qty: 0.5, unit: 'unit', aisle: 'Produce' },
      { item: 'olive oil', qty: 1, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'salt', qty: 0.25, unit: 'tsp', aisle: 'Spices' },
      { item: 'black pepper', qty: 0.25, unit: 'tsp', aisle: 'Spices' },
    ],
    steps: [
      'Dice the onion and bell pepper.',
      'Heat olive oil in a skillet over medium heat and soften the onion and pepper, about 4 minutes.',
      'Add spinach and cook until wilted, about 1 minute.',
      'Whisk the eggs with salt and pepper, pour into the pan and gently scramble until just set.',
      'Serve immediately.',
    ],
  },
  {
    id: 'banana-pancakes',
    name: 'Fluffy Banana Pancakes',
    mealTypes: ['breakfast'],
    tags: ['vegetarian', 'kid-friendly'],
    servings: 2,
    calories: 450,
    prepTime: 10,
    cookTime: 15,
    ingredients: [
      { item: 'flour', qty: 1, unit: 'cup', aisle: 'Condiments & Baking' },
      { item: 'banana', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'milk', qty: 0.75, unit: 'cup', aisle: 'Dairy & Eggs' },
      { item: 'eggs', qty: 1, unit: 'unit', aisle: 'Dairy & Eggs' },
      { item: 'baking powder', qty: 1, unit: 'tsp', aisle: 'Condiments & Baking' },
      { item: 'butter', qty: 1, unit: 'tbsp', aisle: 'Dairy & Eggs' },
    ],
    steps: [
      'Mash the banana in a bowl.',
      'Whisk in milk and egg, then stir in flour and baking powder until just combined.',
      'Melt a little butter in a non-stick pan over medium heat.',
      'Pour 1/4 cup batter per pancake and cook until bubbles form, then flip and cook 1 more minute.',
      'Serve warm with your favourite toppings.',
    ],
  },
  {
    id: 'chicken-caesar',
    name: 'Grilled Chicken Caesar Salad',
    mealTypes: ['lunch', 'dinner'],
    tags: ['high-protein', 'gluten-free'],
    servings: 2,
    calories: 480,
    prepTime: 15,
    cookTime: 15,
    ingredients: [
      { item: 'chicken breast', qty: 2, unit: 'unit', aisle: 'Meat & Seafood' },
      { item: 'romaine lettuce', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'parmesan cheese', qty: 0.25, unit: 'cup', aisle: 'Dairy & Eggs' },
      { item: 'caesar dressing', qty: 4, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'croutons', qty: 1, unit: 'cup', aisle: 'Grains & Pasta' },
      { item: 'olive oil', qty: 1, unit: 'tbsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Rub the chicken breasts with olive oil, salt and pepper.',
      'Grill or pan-sear over medium-high heat for 6-7 minutes per side until cooked through (74°C/165°F).',
      'Let the chicken rest 5 minutes, then slice.',
      'Chop the romaine and toss with dressing, parmesan and croutons.',
      'Top with sliced chicken and serve.',
    ],
  },
  {
    id: 'quinoa-bowl',
    name: 'Mediterranean Quinoa Bowl',
    mealTypes: ['lunch', 'dinner'],
    tags: ['vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    servings: 2,
    calories: 520,
    prepTime: 15,
    cookTime: 20,
    ingredients: [
      { item: 'quinoa', qty: 1, unit: 'cup', aisle: 'Grains & Pasta' },
      { item: 'cucumber', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'cherry tomatoes', qty: 1, unit: 'cup', aisle: 'Produce' },
      { item: 'chickpeas', qty: 1, unit: 'can', aisle: 'Canned Goods' },
      { item: 'red onion', qty: 0.5, unit: 'unit', aisle: 'Produce' },
      { item: 'lemon', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'olive oil', qty: 2, unit: 'tbsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Rinse the quinoa, then simmer in 2 cups water for 15 minutes until fluffy. Let cool slightly.',
      'Dice the cucumber, halve the tomatoes and thinly slice the red onion.',
      'Drain and rinse the chickpeas.',
      'Whisk lemon juice with olive oil, salt and pepper for the dressing.',
      'Combine everything in a bowl, toss with dressing and serve.',
    ],
  },
  {
    id: 'turkey-wrap',
    name: 'Turkey & Hummus Wrap',
    mealTypes: ['lunch'],
    tags: ['high-protein', 'quick'],
    servings: 1,
    calories: 410,
    prepTime: 10,
    cookTime: 0,
    ingredients: [
      { item: 'tortilla wrap', qty: 1, unit: 'unit', aisle: 'Bakery' },
      { item: 'sliced turkey', qty: 4, unit: 'oz', aisle: 'Meat & Seafood' },
      { item: 'hummus', qty: 2, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'spinach', qty: 1, unit: 'cup', aisle: 'Produce' },
      { item: 'tomato', qty: 0.5, unit: 'unit', aisle: 'Produce' },
    ],
    steps: [
      'Spread hummus evenly over the tortilla.',
      'Layer turkey, spinach and sliced tomato down the centre.',
      'Roll up tightly, tucking in the sides.',
      'Slice in half and serve.',
    ],
  },
  {
    id: 'lentil-soup',
    name: 'Hearty Lentil Soup',
    mealTypes: ['lunch', 'dinner'],
    tags: ['vegetarian', 'vegan', 'gluten-free', 'batch-cook'],
    servings: 4,
    calories: 350,
    prepTime: 15,
    cookTime: 35,
    ingredients: [
      { item: 'red lentils', qty: 1.5, unit: 'cup', aisle: 'Grains & Pasta' },
      { item: 'carrot', qty: 2, unit: 'unit', aisle: 'Produce' },
      { item: 'celery', qty: 2, unit: 'unit', aisle: 'Produce' },
      { item: 'onion', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'garlic', qty: 3, unit: 'clove', aisle: 'Produce' },
      { item: 'vegetable broth', qty: 6, unit: 'cup', aisle: 'Canned Goods' },
      { item: 'cumin', qty: 1, unit: 'tsp', aisle: 'Spices' },
      { item: 'olive oil', qty: 2, unit: 'tbsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Dice the onion, carrot and celery; mince the garlic.',
      'Heat olive oil in a large pot and sauté the vegetables until soft, about 8 minutes.',
      'Stir in the garlic and cumin and cook 1 minute until fragrant.',
      'Add lentils and broth, bring to a boil, then simmer 25-30 minutes until the lentils are tender.',
      'Season with salt and pepper. Blend partially for a creamier texture if desired.',
    ],
  },
  {
    id: 'salmon-veg',
    name: 'Baked Salmon with Roasted Vegetables',
    mealTypes: ['dinner'],
    tags: ['high-protein', 'gluten-free', 'pescatarian'],
    servings: 2,
    calories: 560,
    prepTime: 15,
    cookTime: 25,
    ingredients: [
      { item: 'salmon fillet', qty: 2, unit: 'unit', aisle: 'Meat & Seafood' },
      { item: 'broccoli', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'sweet potato', qty: 2, unit: 'unit', aisle: 'Produce' },
      { item: 'olive oil', qty: 2, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'lemon', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'garlic', qty: 2, unit: 'clove', aisle: 'Produce' },
    ],
    steps: [
      'Preheat oven to 200°C/400°F.',
      'Cube the sweet potato and cut broccoli into florets. Toss with half the olive oil, salt and pepper on a baking tray.',
      'Roast the vegetables for 15 minutes.',
      'Place salmon on the tray, drizzle with remaining oil, minced garlic and lemon slices.',
      'Bake 12-15 minutes more until the salmon flakes easily. Serve with a squeeze of lemon.',
    ],
  },
  {
    id: 'stir-fry',
    name: 'Veggie Tofu Stir-Fry',
    mealTypes: ['dinner'],
    tags: ['vegetarian', 'vegan', 'high-protein'],
    servings: 3,
    calories: 430,
    prepTime: 20,
    cookTime: 15,
    ingredients: [
      { item: 'firm tofu', qty: 1, unit: 'block', aisle: 'Dairy & Eggs' },
      { item: 'broccoli', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'bell pepper', qty: 2, unit: 'unit', aisle: 'Produce' },
      { item: 'carrot', qty: 2, unit: 'unit', aisle: 'Produce' },
      { item: 'soy sauce', qty: 3, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'garlic', qty: 3, unit: 'clove', aisle: 'Produce' },
      { item: 'ginger', qty: 1, unit: 'tbsp', aisle: 'Produce' },
      { item: 'rice', qty: 1.5, unit: 'cup', aisle: 'Grains & Pasta' },
    ],
    steps: [
      'Cook the rice according to package directions.',
      'Press and cube the tofu; slice the peppers, carrots and broccoli.',
      'Pan-fry the tofu in a hot oiled wok until golden, then set aside.',
      'Stir-fry the vegetables with minced garlic and ginger for 5-6 minutes.',
      'Return the tofu, add soy sauce and toss to coat. Serve over rice.',
    ],
  },
  {
    id: 'spaghetti-bolognese',
    name: 'Classic Spaghetti Bolognese',
    mealTypes: ['dinner'],
    tags: ['high-protein', 'kid-friendly', 'batch-cook'],
    servings: 4,
    calories: 610,
    prepTime: 15,
    cookTime: 40,
    ingredients: [
      { item: 'spaghetti', qty: 400, unit: 'g', aisle: 'Grains & Pasta' },
      { item: 'ground beef', qty: 500, unit: 'g', aisle: 'Meat & Seafood' },
      { item: 'canned tomatoes', qty: 2, unit: 'can', aisle: 'Canned Goods' },
      { item: 'onion', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'garlic', qty: 3, unit: 'clove', aisle: 'Produce' },
      { item: 'carrot', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'tomato paste', qty: 2, unit: 'tbsp', aisle: 'Canned Goods' },
      { item: 'olive oil', qty: 2, unit: 'tbsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Finely dice the onion, carrot and garlic.',
      'Brown the ground beef in a large pot, then remove and set aside.',
      'Sauté the vegetables in olive oil until soft, then stir in tomato paste.',
      'Return the beef, add canned tomatoes and simmer 30 minutes, stirring occasionally.',
      'Meanwhile cook the spaghetti until al dente. Serve the sauce over the pasta.',
    ],
  },
  {
    id: 'black-bean-tacos',
    name: 'Black Bean Tacos',
    mealTypes: ['dinner', 'lunch'],
    tags: ['vegetarian', 'vegan', 'quick', 'kid-friendly'],
    servings: 3,
    calories: 440,
    prepTime: 15,
    cookTime: 15,
    ingredients: [
      { item: 'corn tortillas', qty: 6, unit: 'unit', aisle: 'Bakery' },
      { item: 'black beans', qty: 2, unit: 'can', aisle: 'Canned Goods' },
      { item: 'avocado', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'red onion', qty: 0.5, unit: 'unit', aisle: 'Produce' },
      { item: 'lime', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'cumin', qty: 1, unit: 'tsp', aisle: 'Spices' },
      { item: 'cilantro', qty: 0.5, unit: 'cup', aisle: 'Produce' },
    ],
    steps: [
      'Drain the black beans and warm them in a pan with cumin, salt and a splash of water.',
      'Mash lightly for a refried texture, or leave whole.',
      'Warm the tortillas in a dry pan.',
      'Slice the avocado, dice the onion and chop the cilantro.',
      'Fill tortillas with beans, top with avocado, onion, cilantro and a squeeze of lime.',
    ],
  },
  {
    id: 'greek-yogurt-parfait',
    name: 'Greek Yogurt & Granola Parfait',
    mealTypes: ['breakfast', 'snack'],
    tags: ['vegetarian', 'quick', 'no-cook', 'high-protein'],
    servings: 1,
    calories: 300,
    prepTime: 5,
    cookTime: 0,
    ingredients: [
      { item: 'greek yogurt', qty: 1, unit: 'cup', aisle: 'Dairy & Eggs' },
      { item: 'granola', qty: 0.5, unit: 'cup', aisle: 'Grains & Pasta' },
      { item: 'mixed berries', qty: 0.5, unit: 'cup', aisle: 'Produce' },
      { item: 'honey', qty: 1, unit: 'tbsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Spoon half the yogurt into a glass or bowl.',
      'Add a layer of granola and berries.',
      'Repeat the layers with the remaining yogurt, granola and berries.',
      'Drizzle with honey and serve.',
    ],
  },
  {
    id: 'chicken-fajita-bowl',
    name: 'Chicken Fajita Bowl',
    mealTypes: ['lunch', 'dinner'],
    tags: ['high-protein', 'gluten-free', 'batch-cook'],
    servings: 3,
    calories: 540,
    prepTime: 20,
    cookTime: 20,
    ingredients: [
      { item: 'chicken breast', qty: 3, unit: 'unit', aisle: 'Meat & Seafood' },
      { item: 'bell pepper', qty: 2, unit: 'unit', aisle: 'Produce' },
      { item: 'onion', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'rice', qty: 1.5, unit: 'cup', aisle: 'Grains & Pasta' },
      { item: 'black beans', qty: 1, unit: 'can', aisle: 'Canned Goods' },
      { item: 'paprika', qty: 1, unit: 'tbsp', aisle: 'Spices' },
      { item: 'cumin', qty: 1, unit: 'tsp', aisle: 'Spices' },
      { item: 'olive oil', qty: 2, unit: 'tbsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Cook the rice according to package directions.',
      'Slice the chicken, peppers and onion into strips.',
      'Toss the chicken with paprika, cumin, salt and pepper.',
      'Sauté the chicken in olive oil until cooked through, then add peppers and onion and cook until tender-crisp.',
      'Build bowls with rice, warmed black beans and the fajita mixture.',
    ],
  },
  {
    id: 'caprese-salad',
    name: 'Caprese Salad',
    mealTypes: ['lunch', 'snack'],
    tags: ['vegetarian', 'gluten-free', 'quick', 'no-cook'],
    servings: 2,
    calories: 280,
    prepTime: 10,
    cookTime: 0,
    ingredients: [
      { item: 'tomato', qty: 3, unit: 'unit', aisle: 'Produce' },
      { item: 'fresh mozzarella', qty: 8, unit: 'oz', aisle: 'Dairy & Eggs' },
      { item: 'fresh basil', qty: 0.5, unit: 'cup', aisle: 'Produce' },
      { item: 'olive oil', qty: 2, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'balsamic vinegar', qty: 1, unit: 'tbsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Slice the tomatoes and mozzarella into rounds.',
      'Arrange alternating slices on a plate, tucking basil leaves between them.',
      'Drizzle with olive oil and balsamic vinegar.',
      'Season with salt and pepper and serve.',
    ],
  },
  {
    id: 'shrimp-pasta',
    name: 'Garlic Shrimp Pasta',
    mealTypes: ['dinner'],
    tags: ['pescatarian', 'high-protein', 'quick'],
    servings: 3,
    calories: 580,
    prepTime: 10,
    cookTime: 20,
    ingredients: [
      { item: 'linguine', qty: 300, unit: 'g', aisle: 'Grains & Pasta' },
      { item: 'shrimp', qty: 400, unit: 'g', aisle: 'Meat & Seafood' },
      { item: 'garlic', qty: 4, unit: 'clove', aisle: 'Produce' },
      { item: 'butter', qty: 2, unit: 'tbsp', aisle: 'Dairy & Eggs' },
      { item: 'lemon', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'parsley', qty: 0.25, unit: 'cup', aisle: 'Produce' },
      { item: 'olive oil', qty: 1, unit: 'tbsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Cook the linguine until al dente, reserving 1/2 cup pasta water.',
      'Melt butter with olive oil in a large pan and sauté minced garlic for 1 minute.',
      'Add the shrimp and cook 2-3 minutes per side until pink.',
      'Toss in the pasta with a splash of pasta water and the lemon juice.',
      'Finish with chopped parsley and serve.',
    ],
  },
  {
    id: 'oatmeal-almond',
    name: 'Almond Butter Oatmeal',
    mealTypes: ['breakfast'],
    tags: ['vegetarian', 'vegan', 'quick'],
    servings: 1,
    calories: 360,
    prepTime: 5,
    cookTime: 5,
    ingredients: [
      { item: 'rolled oats', qty: 0.5, unit: 'cup', aisle: 'Grains & Pasta' },
      { item: 'almond milk', qty: 1, unit: 'cup', aisle: 'Dairy & Eggs' },
      { item: 'almond butter', qty: 1, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'banana', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'cinnamon', qty: 0.5, unit: 'tsp', aisle: 'Spices' },
    ],
    steps: [
      'Combine oats and almond milk in a small pot.',
      'Simmer over medium heat for 4-5 minutes, stirring, until creamy.',
      'Stir in almond butter and cinnamon.',
      'Top with sliced banana and serve.',
    ],
  },
  {
    id: 'stuffed-peppers',
    name: 'Quinoa Stuffed Peppers',
    mealTypes: ['dinner'],
    tags: ['vegetarian', 'gluten-free', 'batch-cook'],
    servings: 4,
    calories: 470,
    prepTime: 20,
    cookTime: 40,
    ingredients: [
      { item: 'bell pepper', qty: 4, unit: 'unit', aisle: 'Produce' },
      { item: 'quinoa', qty: 1, unit: 'cup', aisle: 'Grains & Pasta' },
      { item: 'black beans', qty: 1, unit: 'can', aisle: 'Canned Goods' },
      { item: 'corn', qty: 1, unit: 'cup', aisle: 'Canned Goods' },
      { item: 'shredded cheese', qty: 1, unit: 'cup', aisle: 'Dairy & Eggs' },
      { item: 'canned tomatoes', qty: 1, unit: 'can', aisle: 'Canned Goods' },
      { item: 'cumin', qty: 1, unit: 'tsp', aisle: 'Spices' },
    ],
    steps: [
      'Preheat oven to 190°C/375°F. Cook the quinoa in 2 cups water until fluffy.',
      'Halve the peppers and remove the seeds.',
      'Mix cooked quinoa with black beans, corn, canned tomatoes, cumin and half the cheese.',
      'Fill the pepper halves, top with remaining cheese and place in a baking dish.',
      'Cover with foil and bake 30 minutes, then uncover and bake 10 minutes more.',
    ],
  },
  {
    id: 'beef-stir-fry',
    name: 'Beef & Broccoli',
    mealTypes: ['dinner'],
    tags: ['high-protein'],
    servings: 3,
    calories: 520,
    prepTime: 20,
    cookTime: 15,
    ingredients: [
      { item: 'beef strips', qty: 400, unit: 'g', aisle: 'Meat & Seafood' },
      { item: 'broccoli', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'soy sauce', qty: 3, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'garlic', qty: 3, unit: 'clove', aisle: 'Produce' },
      { item: 'ginger', qty: 1, unit: 'tbsp', aisle: 'Produce' },
      { item: 'cornstarch', qty: 1, unit: 'tbsp', aisle: 'Condiments & Baking' },
      { item: 'rice', qty: 1.5, unit: 'cup', aisle: 'Grains & Pasta' },
    ],
    steps: [
      'Cook the rice according to package directions.',
      'Toss the beef strips with cornstarch and 1 tbsp soy sauce.',
      'Sear the beef in a hot oiled wok until browned, then set aside.',
      'Stir-fry the broccoli with garlic and ginger, adding a splash of water to steam.',
      'Return the beef, add remaining soy sauce, toss and serve over rice.',
    ],
  },
  {
    id: 'minestrone',
    name: 'Vegetable Minestrone',
    mealTypes: ['lunch', 'dinner'],
    tags: ['vegetarian', 'vegan', 'batch-cook'],
    servings: 4,
    calories: 330,
    prepTime: 20,
    cookTime: 35,
    ingredients: [
      { item: 'canned tomatoes', qty: 1, unit: 'can', aisle: 'Canned Goods' },
      { item: 'cannellini beans', qty: 1, unit: 'can', aisle: 'Canned Goods' },
      { item: 'carrot', qty: 2, unit: 'unit', aisle: 'Produce' },
      { item: 'celery', qty: 2, unit: 'unit', aisle: 'Produce' },
      { item: 'zucchini', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'onion', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'small pasta', qty: 1, unit: 'cup', aisle: 'Grains & Pasta' },
      { item: 'vegetable broth', qty: 6, unit: 'cup', aisle: 'Canned Goods' },
    ],
    steps: [
      'Dice all the vegetables.',
      'Sauté onion, carrot and celery in olive oil until soft, about 8 minutes.',
      'Add zucchini, canned tomatoes, beans and broth. Bring to a boil.',
      'Simmer 20 minutes, then add the pasta and cook until tender, about 10 minutes.',
      'Season and serve with a sprinkle of parmesan if desired.',
    ],
  },
  {
    id: 'apple-peanut-snack',
    name: 'Apple Slices with Peanut Butter',
    mealTypes: ['snack'],
    tags: ['vegetarian', 'vegan', 'quick', 'no-cook', 'kid-friendly'],
    servings: 1,
    calories: 220,
    prepTime: 5,
    cookTime: 0,
    ingredients: [
      { item: 'apple', qty: 1, unit: 'unit', aisle: 'Produce' },
      { item: 'peanut butter', qty: 2, unit: 'tbsp', aisle: 'Condiments & Baking' },
    ],
    steps: [
      'Core and slice the apple into wedges.',
      'Serve with peanut butter for dipping.',
    ],
  },
];

// Ordered list of grocery aisles for grouping the shopping list.
const AISLE_ORDER = [
  'Produce',
  'Meat & Seafood',
  'Dairy & Eggs',
  'Bakery',
  'Grains & Pasta',
  'Canned Goods',
  'Condiments & Baking',
  'Spices',
  'Other',
];

// The dietary/preference tags a user can filter suggestions by.
const DIET_FILTERS = [
  'vegetarian',
  'vegan',
  'gluten-free',
  'pescatarian',
  'high-protein',
  'quick',
  'kid-friendly',
];

const MEAL_TYPES = ['breakfast', 'lunch', 'dinner', 'snack'];

function getRecipeById(id) {
  return RECIPES.find((r) => r.id === id) || null;
}
